export const NOTIFICATION_TYPES = [
  "APPOINTMENT_CREATED",
  "APPOINTMENT_REQUESTED",
  "APPOINTMENT_ACCEPTED",
  "APPOINTMENT_REJECTED",
  "APPOINTMENT_CANCELLED",
  "APPOINTMENT_COMPLETED",
  "APPOINTMENT_PAYMENT_RECEIVED",
  "APPOINTMENT_REFUND_CONFIRMED",
  "APPOINTMENT_REFUND_RECEIVED",
  "VIDEO_CONSULTATION_STARTED",
  "MESSAGE_RECEIVED",
  "REVIEW_RECEIVED",
  "REVIEW_REPLY_RECEIVED",
  "REVIEW_REPLY_UPDATED",
  "REVIEW_REPORT_OPENED",
  "REVIEW_REPORT_RESOLVED_HIDDEN",
  "REVIEW_REPORT_RESTORED",
  "REVIEW_REPORT_DISMISSED",
  "PROFESSIONAL_PROFILE_UPDATED",
  "PROFESSIONAL_AVATAR_UPDATED",
  "PROFESSIONAL_DOCUMENT_UPLOADED",
  "PROFESSIONAL_PROFILE_APPROVED",
  "PROFESSIONAL_PROFILE_REJECTED",
] as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[number];

export function isNotificationType(
  value: string
): value is NotificationType {
  return (NOTIFICATION_TYPES as readonly string[]).includes(value);
}
